name: AWS Public ECR Build & Push

on:
  push:
    branches: [main]

jobs:
  ecr-public-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Public ECR is global but uses us-east-1 for token auth

    - name: Login to Amazon ECR Public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public

    - name: Build and Tag Docker Image
      run: |
        docker build -t public.ecr.aws/m3o3o8o0/elomurphy/nodejscodebase:latest .

    - name: Push Docker Image to Public ECR
      run: |
        docker push public.ecr.aws/m3o3o8o0/elomurphy/nodejscodebase:latest

